# Site Settings
github:              [metadata]
paginate:            5
disqus:              #"your-disqus"

# Build settings
# markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:                [jekyll-paginate]

# This will require each of these plugins automatically.
plugins:
  - jekyll-mermaid

mermaid:
src: ./assets/js/mermaid.js
